### ISSUE TITLE
Can't call JavaScript 

### ISSUE THREAD

**Issue by GirkovArpa** [sciter-sdk/rust-sciter#100]
JavaScript cannot be called when using the Sciter.JS library.  Nothing happens, except it returns `Ok(undefined)`.

```rust
fn document_complete(&mut self, root: HELEMENT, _target: HELEMENT) {
  let value = &Element::from(root).call_function("foo", &make_args!("bar"));
  println!("{:?}", value); // Ok(undefined)
}
```

**Comment by pravic** [comment]
http://sciter.com/forums - better to ask there. Sciter.Js have some surprising decisions, so no idea what is working on that version and what isn't.

**Comment by GirkovArpa** [comment]
Very well then.

**Comment by GirkovArpa** [comment]
The workaround I'm using is, since JS can call Rust but not vice-versa, is have JS simply keep asking Rust if it needs to do anything, and act based on the response.

**Comment by pravic** [comment]
Not an efficient decision. What was the answer on sciter forums?

**Comment by GirkovArpa** [comment]
I have not asked yet 😛

**Comment by Nikola526** [comment]
I got it to work with:
```
let root = Element::from_window(frame.get_hwnd()).unwrap();
root.eval_script("Window.this.Test()").unwrap();
```

**Comment by GirkovArpa** [comment]
Got it working with this:

```rust
impl sciter::EventHandler for EventHandler {
    fn get_subscription(&mut self) -> Option<sciter::dom::event::EVENT_GROUPS> {
        Some(
            sciter::dom::event::default_events()
                | sciter::dom::event::EVENT_GROUPS::HANDLE_METHOD_CALL,
        )
    }
}
```

**Comment by pravic** [comment]
@GirkovArpa Wait, the title says "cannot call JS" and you are talking about "cannot be called from JS".
Also, `default_events()` does include `HANDLE_METHOD_CALL` by default: https://github.com/sciter-sdk/rust-sciter/blob/f59030af0a00052a2759ca28667bed24a6448c2d/src/dom.rs#L1487-L1489
