### ISSUE TITLE
Do not support ararch64-apple-osx

### ISSUE THREAD

**Issue by shenjiangqiu** [sciter-sdk/rust-sciter#105]
when compile this on an arm machine, it says:"
78 | #[macro_use] extern crate objc;
   |              ^^^^^^^^^^^^^^^^^^ can't find crate
"

mi

**Comment by pravic** [comment]
By the way, it's `apple-darwin`:

> $ rustup target list | rg apple
aarch64-apple-darwin
aarch64-apple-ios
x86_64-apple-darwin
x86_64-apple-ios
