### ISSUE TITLE
run error for create frame (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by toplinuxsir** [sciter-sdk/rust-sciter#109]
run error for create frame in rust code .
(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by pravic** [comment]
Sciter version?

**Comment by toplinuxsir** [comment]
@pravic Thanks ,I upgrade to 4.4.7 , Everything works ok !
