### ISSUE TITLE
[linux] 'ext' module not found

### ISSUE THREAD

**Issue by Alvarocz** [sciter-sdk/rust-sciter#11]
let p = ext::SciterAPI();
    |               ^^^^^^^^^^^^^^ Use of undeclared type or module `ext`

What happen?? this is from an included example.

**Comment by pravic** [comment]
linux x86 (i686)?

**Comment by Alvarocz** [comment]
Yes!

**Comment by pravic** [comment]
Sciter does not contains build for it: https://github.com/c-smile/sciter-sdk/tree/master/bin.gtk.

x86 supported, as far as I know, just not shipped with public SDK. You can ask about it on http://sciter.com/forums/ about it.

**Comment by Alvarocz** [comment]
Ok, thanks
