### ISSUE TITLE
quick.js has been used by sciter-js-sdk 

### ISSUE THREAD

**Issue by fuyoo** [sciter-sdk/rust-sciter#113]
Those tis based examples don't work in the new SDK.
Do you have any plans to adapt the new SDK?

**Comment by fuyoo** [comment]
i cat find a way to call the rust func in the javascript file..

i  am try interop example
```javascript
const view = Window.this 
view. calc_sum()
```
the console tell me method undefined.

**Comment by superblaubeere27** [comment]
How did you solve this?

**Comment by fuyoo** [comment]
> How did you solve this?
at the rust side impl
```rust
impl sciter::EventHandler for EventHandler {
  fn get_subscription(&mut self) -> Option<sciter::dom::event::EVENT_GROUPS> {
    Some(sciter::dom::event::default_events() | sciter::dom::event::EVENT_GROUPS::HANDLE_METHOD_CALL)
}
```
at the view side:
```javascript
const view = Window.this
view.xcall("sum",1, 2);
```
detail at here [#96](https://github.com/sciter-sdk/rust-sciter/issues/96)

**and the sciter.js doc at here [doc](https://github.com/c-smile/sciter-js-sdk/blob/main/docs/md/index.md)**

**Comment by pravic** [comment]
`default_events()` should be adjusted to cover JS. Will do.

**Comment by fuyoo** [comment]
> `default_events()` should be adjusted to cover JS. Will do.

that's great, thank's a lot!

**Comment by SonnyX** [comment]
Might be nice to release the version with the fix on crates.io :)
