### ISSUE TITLE
How_to_pack_sciter.dll_into_exe

### ISSUE THREAD

**Issue by dobefore** [sciter-sdk/rust-sciter#117]
as above,How to compile sciter.dll into exe?

**Comment by pravic** [comment]
While it is possible theoretically (google how to pack dll into exe), it's very hacky.

Sciter offers a static library if purchased: https://sciter.com/prices/

**Comment by dobefore** [comment]
thanks
,A little bit difficult for me. I just ` include_bytes()` then write to file in windows temp as an alternative.

**Comment by albertoVieiraNeto** [comment]
hi, i have a license for sciter and already generated the sciter.static.lib, how should i proceed to embed the static library to my final executable? can you just give me a direction?
