### ISSUE TITLE
I have new err on compile error.

### ISSUE THREAD

**Issue by iakuf** [sciter-sdk/rust-sciter#118]
$ cargo run --example minimal
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/minimal`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', examples/minimal.rs:18:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by pravic** [comment]
`sciter::set_options ` returns an error? Is this Sciter.JS?

**Comment by iakuf** [comment]
Sciter sdk

**Comment by pravic** [comment]
I mean, Sciter.JS or Sciter.TIS?

**Comment by iakuf** [comment]
$ RUST_BACKTRACE=1 cargo run --example minimal
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/minimal`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', examples/minimal.rs:18:12
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1037:23
   4: minimal::main
             at ./examples/minimal.rs:15:2
   5: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

my library is libsciter.dylib.
 I use Sciter.TIS. 
my set library use DYLD_LIBRARY_PATH

**Comment by pravic** [comment]
I see, thanks. And what Sciter SDK version?

**Comment by iakuf** [comment]
sorry,  my fault. everything is ok if i use new  Sciter SDK

**Comment by pravic** [comment]
Interesting. Was it because of #107?

**Comment by iakuf** [comment]
yes
