### ISSUE TITLE
 confused value type for ArrayBuffer

### ISSUE THREAD

**Issue by armersong** [sciter-sdk/rust-sciter#122]
I found the value of arraybuffer is T_STRING when it is passed from js to native function, i think it should be T_BYTES.  Could you help me to find what is wrong?
detail:
https://sciter.com/forums/topic/confused-value-type-for-arraybuffer/

thanks!

**Comment by pravic** [comment]
> By I know that API will pass new ArrayBuffer(100) as VALUE/T_BYTES

Interesting. Yeah, I'd check that.

**Comment by pravic** [comment]
Well, for me it also claims that it is `T_STRING`: https://sciter.com/forums/topic/confused-value-type-for-arraybuffer/#post-74087
