### ISSUE TITLE
warning! unknown event group with latest sdk

### ISSUE THREAD

**Issue by rustdesk** [sciter-sdk/rust-sciter#128]
Not big issue, but annoying.

**Comment by pravic** [comment]
And what is it exactly? What number does it have?

**Comment by rustdesk** [comment]
[sciter] warning! unknown event group 0020
[sciter] warning! unknown event group 0020

**Comment by rustdesk** [comment]
BTW, could ypu help answer https://sciter.com/forums/topic/menu-not-be-hidden-when-open-dialog-on-linux/#post-75593?

**Comment by pravic** [comment]
Huh. How is 020 unknown if it's a size event 🤔

**Comment by snluu** [comment]
Confirmed that I'm seeing the same thing.

**Comment by pravic** [comment]
It as indeed annoying. Thanks for the catch!
