### ISSUE TITLE
value.rs "ensure_tmp_mut" error

### ISSUE THREAD

**Issue by enp6** [sciter-sdk/rust-sciter#148]
fn ensure_tmp_mut(&self) -> &mut Value {
		let cp = self as *const Value;
		let mp = cp as *mut Value;
		let me = unsafe { &mut *mp };
		return me.ensure_tmp();
	}

&mut *mp There is an error prompt here

casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell`
for more information, visit <https://doc.rust-lang.org/book/ch15-05-interior-mutability.html>
`#[deny(invalid_reference_casting)]` on by defaultrustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B4%5D?4#file%3A%2F%2F%2Fg%253A%2FZProject%2FRust%2FXACC%2Fmain%2Frust-sciter%2Fsrc%2Fvalue.rs)
value.rs(577, 12): casting happend here

**Comment by Martinfx** [comment]
Are you going to fix this undefined behavior?

**Comment by Martinfx** [comment]
> ```
> fn ensure_tmp_mut(&self) -> &mut Value {
> 	let cp = self as *const Value;
> 	let mp = cp as *mut Value;
> 	let me = unsafe { &mut *mp };
> 	return me.ensure_tmp();
> }
> ```
> 
> &mut *mp There is an error prompt here
> 
> casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell` for more information, visit https://doc.rust-lang.org/book/ch15-05-interior-mutability.html `#[deny(invalid_reference_casting)]` on by defaultrustcClick for full compiler diagnostic value.rs(577, 12): casting happend here

You try add #[allow(invalid_reference_casting)]

**Comment by enp6** [comment]
@Martinfx 
#[allow(invalid_reference_casting)]
This method works, it compiles successfully without modification! Thanks.
