### ISSUE TITLE
TWO windows appear

### ISSUE THREAD

**Issue by hasanOryx** [sciter-sdk/rust-sciter#21]
I tried loading the `minimal.html`, it is loading fine at `cargo run`, but once I runn the `.exe` alone, 2 windows appear, one empty as `cmd` and one shows the real output as shown in this pic.

I'm using `Windows 10`

![image](https://user-images.githubusercontent.com/26045838/33518749-a8dfdfbc-d7ab-11e7-986b-f3c218d01e5f.png)

**Comment by pravic** [comment]
Read this: [minimal.rs](https://github.com/sciter-sdk/rust-sciter/blob/master/examples/minimal.rs#L3..L6).

If you use Rust 1.18 or higher, put this line in your app: `#![windows_subsystem="windows"]`.
It will make a windows application without console window.

**Comment by hasanOryx** [comment]
Thanks @pravic
