### ISSUE TITLE
Child window support?

### ISSUE THREAD

**Issue by Boscop** [sciter-sdk/rust-sciter#24]
How to create a child window from a given parent `HWND`?

Like this: https://sciter.com/tag/child-window/

**Comment by pravic** [comment]
Your question is not clear. 

The [`Window::create`](https://docs.rs/sciter-rs/0.4.25/sciter/window/struct.Window.html#method.create) method would be the answer if you wanted to create a sciter window as a child of another window (native or sciter's).

But your link is about a foreign native child inside a sciter window. So, it's basically the same then, `wnd.get_hwnd ()` and there we are.

**Comment by Boscop** [comment]
Thanks!

Btw, is there a way to compile JS to tiscript? (So that I can use languages that compile to JS.)

**Comment by pravic** [comment]
There is no way (as far as I know).
