### ISSUE TITLE
minimal.rs example is broken on Sciter 4.2.5.0 or newer.

### ISSUE THREAD

**Issue by Hand-of-Cthulhu** [sciter-sdk/rust-sciter#46]
Because of 4.2.5.0[ disabling some unsafe features](https://rawgit.com/c-smile/sciter-sdk/7036a9c7912ac30d9f369d9abb87b278d2d54c6d/logfile.htm) by default, the minimal example now 

- Can't open files
- Can't connect to inspector
- Displays "Running on _undefined_ machine"

Being new to Sciter I had to stare at some really opaque error messages for a while (which don't even show up by default because #![windows_subsystem = "windows"]) to figure out what's going on. 

Do we want to add 
```
sciter::set_options(sciter::RuntimeOptions::ScriptFeatures(
		    sciter::SCRIPT_RUNTIME_FEATURES::ALLOW_SYSINFO as u8 |  // Enables Sciter.machineName()
		    sciter::SCRIPT_RUNTIME_FEATURES::ALLOW_FILE_IO as u8 | // Enables opening file dialog
		    sciter::SCRIPT_RUNTIME_FEATURES::ALLOW_SOCKET_IO as u8)).unwrap(); // Enables connecting to inspector
```

or should we just remove these things (file opener, machineName(), inspector) from the minimal.rs example.

Personally think showing this early is pretty important, because Sciter's own documentation don't seem to show any of this, and the error messages all just say the functions are undefined.

I'll probably make a PR for this.

**Comment by pravic** [comment]
Yes, you are right. 

I've been thinking about this as well, but probably it'd be better to enable this by default (as I do for debugging) with an ability to opt-out.

**Comment by ngirard** [comment]
This issue should be closed as fixed.
