### ISSUE TITLE
[Question] How to load files as binary data other than the html file?

### ISSUE THREAD

**Issue by Hand-of-Cthulhu** [sciter-sdk/rust-sciter#48]
Is there a way to load files like how the html file is loaded in the examples.
```
let mut frame = sciter::Window::new();
frame.load_html(html_vec, Some("some/path"));
```

But for other files like fonts or css files?

**Comment by pravic** [comment]
Think of a document viewer. If you load an HTML file, it would display it on window (and its associated resources, like images, fonts, or styles). If you loaded a CSS file, what would you expect to see? Its [text](https://sciter.com/screenshots/slide-sciter-ide.png)?

I think, you want the following instead:

```html
<html>
  <head>
    <style type="text/css">
      /* include styles */
      @import url(styles.css);

      /* include fonts */
      @font-face {
        font-family: 'FontAwesome';
        src: url(fontawesome-webfont.ttf);
        font-weight: normal;
        font-style: normal;
      }  
    </style>

    <script type="text/tiscript">
      /* include additional scripts */
      include "script.tis";

      debug "hello, world";
    </script>
```

So, if you have the following structure:

```
| `-- main.html
| `-- script.tis
| `-- styles.css
```

Then you could load everything with a single call:

```rust
// Sciter requires absolute paths when loading HTML.
let mut cwd = std::env::current_dir()?;
cwd.push("main.html");

frame.load_file(cwd.to_str()?);
```

**Comment by Hand-of-Cthulhu** [comment]
Well, what I'm trying to do is include the source files (html css fonts tis...etc) within the binary rather than in a separate folder alongside it.

With the `load_html` function, I can use include_str! macro to include the html file and when distributing I can just send the standalone executable, my question is is there a way to do the same for the other files without in-lining everything.

Thanks.

**Comment by pravic** [comment]
I see. Use packaged resources: [ZIP archives](https://sciter.com/zip-resource-packaging-in-sciter/) or [Sciter archive](https://github.com/sciter-sdk/rust-sciter/blob/master/examples/archived.rs) with `packfolder` packer.

**Comment by Hand-of-Cthulhu** [comment]
`packfolder` seems to be what I'm looking for, thanks!
