### ISSUE TITLE
You might need a LICENSE file?

### ISSUE THREAD

**Issue by DevJac** [sciter-sdk/rust-sciter#50]
I notice you intend to release `rust-sciter` under an MIT license. (And Sciter Engine has it's own separate license).
The README links to https://opensource.org/licenses/MIT, but if you go there you'll notice it's just a template. In my opinion, the problem is specifically that the copyright notice is incomplete in the template.
To illustrate the problem another way. When I comply with the MIT license and include the copyright, should I include `Copyright <YEAR> <COPYRIGHT HOLDER>` literally in my project? I don't know know who else to list as the copyright holder. I would expect to use an actual year, not `<YEAR>`, and ascribe the copyright to a person or organization instead of `COPYRIGHT HOLDER`.
I am not a lawyer though, so maybe my understanding is wrong.
Thanks for your consideration of this and for Sciter, I'm excited to use it.

**Comment by pravic** [comment]
Closed in #51
