### ISSUE TITLE
Dead link in Readme

### ISSUE THREAD

**Issue by ShalokShalom** [sciter-sdk/rust-sciter#57]
Hi :)

Your screenshot link is misleading:
It leads to main Go implementation.

**Comment by pravic** [comment]
Hey.

1) No, [the link](https://github.com/sciter-sdk/go-sciter#sciter-desktop-ui-examples) isn't dead
2) Yes, it leads to the repository with Go bindings, but it's because that repo contains those screenshots. I can't make a link to the original gallery from https://sciter.com.
