### ISSUE TITLE
`sciter::Window::new().load_file(url)` misbehaving

### ISSUE THREAD

**Issue by SonnyX** [sciter-sdk/rust-sciter#63]
In more recent versions of Sciter, `sciter::Window::new().load_file(url)` seems to be broken when using characters in the `url` that get converted to their special counterpart e.g. `spacebar` to `%20`.
For example the following Warning pops up:
`WARNING:DOM: failed to load "/home/sonny/git/Launcher/target/release/new%20theme/frontpage.htm" file, error=2`

This is atleast the case for the sciter releases from 6th of june and 8th of june. Both for windows and linux.
Sciter itself can load the files fine (tested using usciter, both from command line and using the interface)

**Comment by c-smile** [comment]
This: /home/sonny/git/Launcher/target/release/new%20theme/frontpage.htm is not a url but path.

So either: "file:///home/sonny/git/Launcher/target/release/new%20theme/frontpage.htm" or 
"/home/sonny/git/Launcher/target/release/new theme/frontpage.htm"

**Comment by SonnyX** [comment]
@c-smile That's the thing, both
```frame.load_file(&"file:///home/sonny/git/Launcher/target/release/new theme/frontpage.htm");```
and
```frame.load_file(&"/home/sonny/git/Launcher/target/release/new theme/frontpage.htm");```
give the exact same error, as the one mentioned above.

If I would use the `file:///home/sonny/git/Launcher/target/release/new%20theme/frontpage.htm`, it gives me the error:
```WARNING:DOM: failed to load "/home/sonny/git/Launcher/target/release/new%2520theme/frontpage.htm" file, error=2```

**Comment by SonnyX** [comment]
I used to convert `spacebar` to it's hyperlink counterpart '%20' myself before, however since a certain Sciter release this is no longer needed for both 'file://absolute_path' and for 'absolute_path'. 
Converting this yourself would even break things as Sciter would then translate it to `%2520` where the Sciter release from approximately 2 months ago didn't do that.

In any case, except for that change I made a mistake myself, working with symlinks made me forget that renaming the directory does not redirect the symlink, thus the directory did not exist either.

**Comment by c-smile** [comment]
Just in case, tested these on latest version (4.3.0.6):
```
  ::SciterLoadFile(wnd, L"C:/Users/Andrew/Desktop/tests/with spaces/document.htm");
  ::SciterLoadFile(wnd, L"file://C:/Users/Andrew/Desktop/tests/with%20spaces/document.htm");
  ::SciterLoadFile(wnd, L"file://C:/Users/Andrew/Desktop/tests/with spaces/document.htm");
```
all of them load the file successfully.
