### ISSUE TITLE
what is the possible causes for memory leak

### ISSUE THREAD

**Issue by coolit** [sciter-sdk/rust-sciter#67]
Hi there, I get some data from a specific api, pass them as string to sciter,  and update these data in sciter tables. In EventHandler, I write a function for doing this in a loop mode.
But memory leak occurred, memory usage would increase by about 0.1mb/sec.
Is this normal? If not, any idea how to fix it?
Thanks a lot.

**Comment by pravic** [comment]
Hey, sorry for the late reply.

If it's still relevant, could you provide a sample to reproduce?

**Comment by coolit** [comment]
Hi sorry to reply late. Irrelevant so far, will reopen if needs arise.
