### ISSUE TITLE
Is it possible to add the feature of DrawText?

### ISSUE THREAD

**Issue by coolit** [sciter-sdk/rust-sciter#68]
It seems currently there is no such feature. I call tiscript function to draw the text, but this method takes a lot more cpu. So hopefully this feature could be supported at your early convenience. Thanks.

**Comment by pravic** [comment]
Okay

**Comment by coolit** [comment]
I tried the latest example of clock, but it didn't work on win10 64bit. Result as below:
INFO:TIS: initial time: new Date("2019-12-01T18:18:49+08:00") [18,18,49]
set current time from object:array:[18,18,49]
error: process didn't exit successfully: `D:/rust_build/sciter/release\examples\clock.exe` (exit code: 0xc000041d)

**Comment by pravic** [comment]
What was the sciter version?

**Comment by coolit** [comment]
I have updated to the latest version of sciter. Everything worked fine. Thanks for your quick response and efforts.

**Comment by pravic** [comment]
Ah, the crash you mentioned was in old versions: https://sciter.com/forums/topic/textcreateforelement-causes-access-violation/
