### ISSUE TITLE
Live reloading

### ISSUE THREAD

**Issue by asv1** [sciter-sdk/rust-sciter#72]
I'm trying implement live reload and can't do that. Because separate thread must be spawned for directory watching and sciter::Window cannot be shared between threads. Any suggestions?

**Comment by pravic** [comment]
You can share a `dom::Element`, and then fire a corresponding event to trigger reloading. Something like element - fire event - event handler - reload.

It would be even better with (i)frames if possible.

**Comment by asv1** [comment]
Thanks for idea. I done with EventHandler and document_complete.
