### ISSUE TITLE
File Drag/Drop not working

### ISSUE THREAD

**Issue by GirkovArpa** [sciter-sdk/rust-sciter#95]
I posted a thread [here at sciter.com/forums](https://sciter.com/forums/topic/file-drag-drop-not-working-from-rust) about this.  Apparently I have to call `OleInitialize`, but [platform.rs](https://github.com/sciter-sdk/rust-sciter/blob/d7b5a990c04b2284a48698b807d03980e4f27d3d/src/platform.rs) already has a call to that function.  Do I need to call it again somewhere?

**Update**

> [On Windows, drag and drop is now optional and must be enabled with `WindowBuilderExtWindows::with_drag_and_drop(true)`](https://github.com/sciter-sdk/rust-sciter/pull/90)

I am not sure if this is important ...

**Comment by GirkovArpa** [comment]
Drag and drop works when the compiled executable in `/target` is run directly (double-clicking), but not from the command line (`cargo run`).  

I think it would be very helpful to note this somewhere.

**Comment by pravic** [comment]
> Drag and drop works when the compiled executable in /target is run directly (double-clicking), but not from the command line (cargo run).

There should be no difference, to be honest.
